name: 'GitHub Action for Trello'
author: 'kjgarza'
description: 'Automatically pull Github issues into Trello using ProductBaord webhooks event'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
  event:
    description: 'The name of the event'
    required: true
    default: 'github_issue'
  key:
    description: 'Your secret ProductBaord webhooks key'
    required: true
    default: 'EoNxVmkmo3cxJQct-8MvT'
  productboard-token:
    description: 'Your secret ProductBaord Token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'gray-dark'
  icon: 'list'
