name: 'GitHub Action for Trello'
author: 'Muhammad Awais'
description: 'Automatically pull Github issues into Trello using IFTTT webhooks event'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
  event:
    description: 'The name of the event'
    required: true
    default: 'github_issue'
  key:
    description: 'Your secret IFTTT webhooks key'
    required: true
    default: 'EoNxVmkmo3cxJQct-8MvT'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'gray-dark'
  icon: 'list'
