name: 'GitHub Action for ProductBoard'
author: 'kjgarza'
description: 'Automatically pull Github issues into ProductBoard using ProductBaord webhooks event'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
  event:
    description: 'The name of the event'
    required: true
    default: 'github_issue'
  productboardtoken:
    description: 'Your secret ProductBoard Token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'gray-dark'
  icon: 'list'
